# Generated by Django 4.2.5 on 2023-11-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_logo_city_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether the user is an admin.'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(unique=True, upload_to='city_logo/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(unique=True, upload_to='photos/'),
        ),
    ]
