# Generated by Django 4.2.5 on 2023-11-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_superuser_alter_logo_image_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='is_staff',
        ),
    ]
