# Generated by Django 4.2.5 on 2023-11-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='municipality',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.logo'),
        ),
    ]
