# Generated by Django 4.2.5 on 2023-11-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_municipality_logo_url_municipality_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.municipality'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='city_logo/default.png', unique=True, upload_to='user_logo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='logo',
            field=models.ImageField(unique=True, upload_to='city_logo/'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(unique=True, upload_to='municipality_logo/'),
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
