# Generated by Django 4.2.5 on 2023-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_position_municipality_user_logo_alter_city_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='logo',
            field=models.ImageField(default='city_logo/default.png', upload_to='city_logo/'),
        ),
    ]
