# Generated by Django 4.2.5 on 2023-11-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(null=True, unique=True, upload_to='user_logo/'),
        ),
    ]
