# Generated by Django 4.2.5 on 2023-11-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default=None, null=True, unique=True, upload_to='user_logo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='municipality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.municipality'),
        ),
    ]
