# Generated by Django 4.2.5 on 2023-11-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_logo_alter_user_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина')], default=('M', 'Мужчина')),
        ),
    ]
