# Generated by Django 4.2.5 on 2023-11-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='user_logo/'),
        ),
    ]
