# Generated by Django 4.2.5 on 2023-11-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
