# Generated by Django 4.2.5 on 2023-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_news_author_news_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='user_logo/default.png', null=True, upload_to='user_logo/'),
        ),
    ]
