# Generated by Django 4.2.5 on 2023-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='logo',
            field=models.ImageField(default='static/city_logo/default.png', upload_to='static/city_logo/'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(default='static/', upload_to='static/municipality_logo/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(unique=True, upload_to='static/photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='static/user_logo/default.png', null=True, upload_to='static/user_logo/'),
        ),
    ]
