# Generated by Django 4.2.5 on 2023-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_city_logo_alter_municipality_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(default='static/municipality/default.png', upload_to='static/municipality_logo/'),
        ),
    ]
