# Generated by Django 4.2.5 on 2023-11-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_appeal_is_answered_alter_news_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.city'),
        ),
    ]
