# Generated by Django 4.2.5 on 2023-11-26 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_appeal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
