# Generated by Django 4.2.5 on 2023-11-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_appeal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealanswer',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
