# Generated by Django 4.2.5 on 2023-11-26 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_appealanswer_is_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealanswer',
            name='appeal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='user.appeal'),
        ),
    ]
