# Generated by Django 4.2.5 on 2023-11-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_appealanswer_appeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appealanswer',
            name='is_answered',
        ),
    ]
