# Generated by Django 4.2.5 on 2023-11-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_appealanswer_is_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='municipality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.municipality'),
        ),
    ]
